### ISSUE TITLE
escaping quotes

### ISSUE THREAD

**Issue by IngeniariusSoftware** [polystat/c2eo#288]
https://github.com/c-testsuite/c-testsuite/blob/5c7275656d751de0e68b2d340a95b5681858ed07/tests/single-exec/00217.c#L13

c code:
![image](https://user-images.githubusercontent.com/33983579/182136630-b81a4d14-4bae-4408-8929-66f7a0b980d8.png)

eo code:
![image](https://user-images.githubusercontent.com/33983579/182136860-3ad9ad6a-6778-4c21-9f1c-a990c8f52b63.png)

result:
![image](https://user-images.githubusercontent.com/33983579/182137037-b1072738-33cf-41b8-924a-46947dcd7c7b.png)

**Comment by nkchuykin** [comment]
Fix this bug in #289
