### ISSUE TITLE
fix array initialization

### ISSUE THREAD

**Issue by IngeniariusSoftware** [polystat/c2eo#316]
now skipped:
https://github.com/polystat/c2eo/blob/05e5fb7e9867fb443450c290fac924d504f4464e/project/scripts/data/skips/testcuite.txt#L10

test example:
https://github.com/c-testsuite/c-testsuite/blob/master/tests/single-exec/00092.c
```c
int a[] = {5, [2] = 2, 3};

int
main()
{
	if (sizeof(a) != 4*sizeof(int))
		return 1;
		
	if (a[0] != 5)
		return 2;
	if (a[1] != 0)
		return 3;
	if (a[2] != 2)
		return 4;
	if (a[3] != 3)
		return 5;
	
	return 0;
}
```

https://github.com/c-testsuite/c-testsuite/blob/master/tests/single-exec/00151.c
```c
int arr[][3][5] = {
	{
		{ 0, 0, 3, 5 },
		{ 1, [3] = 6, 7 },
	},
	{
		{ 1, 2 },
		{ [4] = 7, },
	},
};

int
main(void)
{
	return !(arr[0][1][4] == arr[1][1][4]);
}
```

**Comment by yairyabtsev** [comment]
https://github.com/polystat/c2eo/pull/333

**Comment by IngeniariusSoftware** [comment]
@yairyabtsev, если решено, то эти тесты должны проходить, нужно убрать эту строку из пропуска

https://github.com/polystat/c2eo/blob/05e5fb7e9867fb443450c290fac924d504f4464e/project/scripts/data/skips/testcuite.txt#L10

**Comment by yairyabtsev** [comment]
https://github.com/polystat/c2eo/pull/334
