### ISSUE TITLE
Let's add how to install GTest to Readme

### ISSUE THREAD

**Issue by nkchuykin** [polystat/c2eo#321]
https://github.com/polystat/c2eo/blob/ee517bedc2eed28da1cdb7ae5d1f2d9a2d0ddbb5/.github/workflows/build.yml#L58

**Comment by yairyabtsev** [comment]
```bash
sudo apt-get install libgtest-dev
sudo apt-get install googletest
cd /usr/src/googletest
sudo cmake .
sudo make
cd lib
sudo cp *.a /usr/local/lib
```
or [RU manual](https://russianblogs.com/article/4396765107/)
