### ISSUE TITLE
Initializing of pointers is not working as needed

### ISSUE THREAD

**Issue by nkchuykin** [polystat/c2eo#328]
Аналогичная проблема с инициализацией указателей и указателей на указатели. Но именно с инициализацией значением. Видимо и с другими типами она может возникнуть. Включая внутри массивов и структур (https://github.com/polystat/c2eo/tree/master/project/tests/in_progress/for_main/bad/variables/init/pointer/).

**Comment by yairyabtsev** [comment]
#343
