### ISSUE TITLE
segfault at address 0x30 while tool run

### ISSUE THREAD

**Issue by IngeniariusSoftware** [polystat/c2eo#362]
remove the line if it fixed in the [testcuite](https://github.com/polystat/c2eo/blob/4d9d0fe090817d487e9631a272dcf6e55331094e/project/scripts/data/skips/testcuite.txt):
`00130: TODO segfault at address 0x30 while tool run`

tests:
https://github.com/c-testsuite/c-testsuite/blob/master/tests/single-exec/00130.c

```c
int
main()
{
	char arr[2][4], (*p)[4], *q;
	int v[4];

	p = arr;
	q = &arr[1][3];
	arr[1][3] = 2;
	v[0] = 2;

	if (arr[1][3] != 2)
		return 1;
	if (p[1][3] != 2)
		return 1;
	if (*q != 2)
		return 1;
	if (*v != 2)
		return 1;

	return 0;
}
```

**Comment by LeDron12** [comment]
Неверно происходит работа с char, обращение к элементам поправил
