### ISSUE TITLE
00148.c array in structure

### ISSUE THREAD

**Issue by IngeniariusSoftware** [polystat/c2eo#376]
remove the test from the line if it fixed in the [testcuite](https://github.com/polystat/c2eo/blob/4d9d0fe090817d487e9631a272dcf6e55331094e/project/scripts/data/skips/testcuite.txt):
`00091, 00148: TODO array in structure`

the test:
https://github.com/c-testsuite/c-testsuite/blob/master/tests/single-exec/00148.c

```c
struct S {int a; int b;};
struct S arr[2] = {[1] = {3, 4}, [0] = {1, 2}};

int
main()
{
	if(arr[0].a != 1)
		return 1;
	if(arr[0].b != 2)
		return 2;
	if(arr[1].a != 3)
		return 3;
	if(arr[1].b != 4)
		return 4;
	return 0;
}

```

**Comment by LeDron12** [comment]
Неверно считается размер структуры при инициализации
