### ISSUE TITLE
Program start searching

### ISSUE THREAD

**Issue by EugeneDar** [polystat/c2eo#435]
When I run `./c2eo <path-to-c-file-name> <eo-file-name>.eo` which script do I run? I could not find this information in the project documentation.

**Comment by EugeneDar** [comment]
May be we should add this information to readme file.

**Comment by IngeniariusSoftware** [comment]
@EugeneDar as far as I understand, you mean this section https://github.com/polystat/c2eo#making-changes .
It seems that the answer to your question is also written there?

**Comment by EugeneDar** [comment]
@IngeniariusSoftware we have information about transpiler, but what if I want to add/change command line ’c2eo ...’?

**Comment by IngeniariusSoftware** [comment]
@EugeneDar you are making changes to the source files
