### ISSUE TITLE
We must reduce the readme

### ISSUE THREAD

**Issue by EugeneDar** [polystat/c2eo#441]
To my knowledge, readme file should contain short instruction how to start use the the project and some examples of using. But here we have almost full documentation. I think we should drastically reduce size of readme, and create a separate file for detailed documentation.

**Comment by EugeneDar** [comment]
@yegor256 what do you think?

**Comment by yegor256** [comment]
@EugeneDar we tend to keep everything in one file (README), for better nagivation
