### ISSUE TITLE
Specify docker image tag

### ISSUE THREAD

**Issue by volodya-lombrozo** [polystat/c2eo#443]
I was trying to start compiler using Docker with the next command (from `README`):
```
docker run -v $(pwd):/eo yegor256/c2eo hello.c hello.eo
```
and got the next exception:
```
Using default tag: latest
Error response from daemon: manifest for yegor256/c2eo:latest not found: manifest unknown: manifest unknown
```
Apparently, because `yegor256/c2eo` doesn't have `latest` tag.
If I specify tag with `0.1.24`, then everything works fine:

```
docker run -v $(pwd):/eo yegor256/c2eo:0.1.24 hello.c hello.eo
```
I believe it would be nice to update README or release each new docker image with `latest` tag.

**Comment by IngeniariusSoftware** [comment]
@volodya-lombrozo, thanks, fixed
